spring:
  application.name: consumer
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    servlet:
      path: /api
feign:
  client:
    email: demo@financialhouse.io
    password: cjaiU8CV
    url: https://sandbox-reporting.rpdpymnt.com/api/v3/
    auth:
      url: https://sandbox-reporting.rpdpymnt.com/api/v3/merchant/user/login
logging:
  level:
    com.reporting.consumer.client: DEBUG
    feign: DEBUG